version: '3.9'

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    restart: always
    ports:
      - 9000:9000
      - 9090:9090
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_NOTIFY_KAFKA_ENABLE_CONFLUENT: "on"
      MINIO_NOTIFY_KAFKA_BROKERS_CONFLUENT: "${CONFLUENT_SERVER}"
      MINIO_NOTIFY_KAFKA_TOPIC_CONFLUENT: "minio"
      MINIO_NOTIFY_KAFKA_SASL_USERNAME_CONFLUENT: "${CONFLUENT_API_KEY}"
      MINIO_NOTIFY_KAFKA_SASL_PASSWORD_CONFLUENT: "${CONFLUENT_API_SECRET}"
      MINIO_NOTIFY_KAFKA_SASL_MECHANISM_CONFLUENT: "PLAIN"
      MINIO_NOTIFY_KAFKA_SASL_CONFLUENT: "on"
      MINIO_NOTIFY_KAFKA_TLS_CONFLUENT: "on"
    volumes:
      - ./minio:/data
    command: server /data --console-address ":9090"
