[tool.coverage.run]
branch = true
source = [ "cornery" ]

[tool.coverage.report]
exclude_lines = ['if TYPE_CHECKING:']
show_missing = true

[tool.pytest.ini_options]
addopts = "--cov --cov-fail-under=100 --cov-report html:'../../coverage/packages/cornery/html' --cov-report xml:'../../coverage/packages/cornery/coverage.xml' --junitxml='../../reports/packages/cornery/unittests/junit.xml' --html='../../reports/packages/cornery/unittests/html/index.html'"

[tool.poetry]
name = "corner-detector"
version = "1.0.0"
description = "Lambda function to detect corners of document images"
authors = [ ]
license = 'Proprietary'
readme = 'README.md'

  [[tool.poetry.packages]]
  include = "cornery"

  [tool.poetry.dependencies]
  python = ">=3.8,<3.10"
  numpy = "^1.24.2"
  opencv-python = "^4.7.0.72"
  boto3 = "^1.26.87"

  

[build-system]
requires = ["poetry-core==1.1.0"]
build-backend = "poetry.core.masonry.api"
